{
 "title": "Apache Traffic Server Dashboard",
 "description": "Fixed dashboard for Apache Traffic Monitor 8.x.x and Grafana 7",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughout",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "User Agent Response Bytes per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(proxy_process_http_user_agent_total_response_bytes[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Origin Server Response Bytes per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(proxy_process_http_origin_server_total_response_bytes[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(proxy_process_http_get_requests[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(proxy_process_http_head_requests[1m])",
     "legendFormat": "head"
    },
    {
     "expr": "increase(proxy_process_http_put_requests[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(proxy_process_http_post_requests[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "increase(proxy_process_http_delete_requests[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(proxy_process_http_purge_requests[1m])",
     "legendFormat": "purge"
    }
   ]
  },
  {
   "title": "User Agent Request Delay per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(proxy_process_http_total_transactions_time[1m]) / increase(proxy_process_http_completed_requests[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Concurrent Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "proxy_process_http_current_client_connections",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Write Throughput per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_KB_write_per_sec"
    }
   ]
  },
  {
   "title": "Read Throughput per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_KB_read_per_sec"
    }
   ]
  },
  {
   "title": "HTTP Response Size Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(proxy_process_http_response_document_size_100[1m])",
     "legendFormat": "0-100B"
    },
    {
     "expr": "increase(proxy_process_http_response_document_size_1K[1m])",
     "legendFormat": "100B-1K"
    },
    {
     "expr": "increase(proxy_process_http_response_document_size_3K[1m])",
     "legendFormat": "1K-3K"
    },
    {
     "expr": "increase(proxy_process_http_response_document_size_5K[1m])",
     "legendFormat": "3K-5K"
    },
    {
     "expr": "increase(proxy_process_http_response_document_size_10K[1m])",
     "legendFormat": "5K-10K"
    },
    {
     "expr": "increase(proxy_process_http_response_document_size_1M[1m])",
     "legendFormat": "10K-1M"
    },
    {
     "expr": "increase(proxy_process_http_response_document_size_intf[1m])",
     "legendFormat": "1M+"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_http_cache_deletes",
     "legendFormat": "delete"
    },
    {
     "expr": "proxy_process_http_cache_lookups",
     "legendFormat": "lookup"
    },
    {
     "expr": "proxy_process_http_cache_updates",
     "legendFormat": "update"
    },
    {
     "expr": "proxy_process_http_cache_writes",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Total Bytes Served(ORIG)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_http_origin_server_total_response_bytes"
    }
   ]
  },
  {
   "title": "Total Bytes Served(TS)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_http_user_agent_total_response_bytes"
    }
   ]
  },
  {
   "title": "Total Cache Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Cache Hit Ratio(No.)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_total_hits/(proxy_process_cache_total_hits+proxy_process_cache_total_misses)",
     "legendFormat": "Overall Hit Ratio"
    },
    {
     "expr": "increase(proxy_process_cache_total_hits[1m]) / (increase(proxy_process_cache_total_hits[1m]) + increase(proxy_process_cache_total_misses[1m]))",
     "legendFormat": "Recent Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Total Hits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_process_cache_total_hits" }
   ]
  },
  {
   "title": "Cache Total Misses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_total_misses"
    }
   ]
  },
  {
   "title": "Cache Bytes Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_process_cache_bytes_used" }
   ]
  },
  {
   "title": "Total Cache Hit Ratio(Bytes.)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_total_hits_bytes/(proxy_process_cache_total_hits_bytes+proxy_process_cache_total_misses_bytes)",
     "legendFormat": "Overall Hit Ratio"
    },
    {
     "expr": "increase(proxy_process_cache_total_hits_bytes[1m]) / (increase(proxy_process_cache_total_hits_bytes[1m]) + increase(proxy_process_cache_total_misses_bytes[1m]))",
     "legendFormat": "Recent Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Total Hit Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_total_hits_bytes"
    }
   ]
  },
  {
   "title": "Cache Total Miss Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_total_misses_bytes"
    }
   ]
  },
  {
   "title": "Cache Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_bytes_total"
    }
   ]
  },
  {
   "title": "RAM Cache Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hit RAM Ratio(No.)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_ram_cache_hits/(proxy_process_cache_ram_cache_hits+proxy_process_cache_ram_cache_misses)",
     "legendFormat": "Overall Hit Ratio"
    },
    {
     "expr": "increase(proxy_process_cache_ram_cache_hits[1m]) / (increase(proxy_process_cache_ram_cache_hits[1m]) + increase(proxy_process_cache_ram_cache_misses[1m]))",
     "legendFormat": "Recent Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache RAM Total Hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_ram_cache_hits"
    }
   ]
  },
  {
   "title": "Cache RAM Bytes Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_ram_cache_bytes_used",
     "legendFormat": "Ram Used"
    }
   ]
  },
  {
   "title": "Cache Total Misses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_ram_cache_misses"
    }
   ]
  },
  {
   "title": "Cache RAM Bytes Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxy_process_cache_ram_cache_total_bytes"
    }
   ]
  }
 ]
}